docs/commands.md
Add note how to change the output folder for the temporary files and folders.
=> docs: add note how to change temp folder

examples/simple-with-external-repos/.kluctl.yml
Add simple example for config with external repos. You can add the external projects to your namespace if you like or we create a separate project namespace for kluctl.
=> feat(examples): add example with external repos

docs/deployments.md
Fixed typos in `docs/deployments.md`
=> docs: fix minor typos in `docs/deployments.md`

.github/ISSUE_TEMPLATE/BUG.yml, .github/ISSUE_TEMPLATE/FEATURE.yml, .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST.md
This PR adds templates for bug reports, feature requests and pull requests
=> Add templates for bug reports, feature requests and pull requests

.github/ISSUE_TEMPLATE/FEATURE.yml
Signed-off-by: Aljoscha Pörtner <aljoscha.poertner@posteo.de>
This PR fixes an error with the options in the feature request template.
=> chore: put all options in feature request template in quotes

README.md
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #21 (issue)
In the [README](https://github.com/kluctl/kluctl/blob/main/README.md), there is a typo on line 18.
It states "CI/CI pipelines", however it should state "CI/CD pipelines".
I also feel like having the info about tools compatibility and no cluster-side components should be placed above the list of features, especially given the length of the features list. Those could be a decision factor on whether this tool should be used.
=> README layout improvements & fix typo

pkg/k8s/k8s_cluster.go
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> fix: Remove redundant imports

cmd/kluctl/args/project.go, cmd/kluctl/commands/utils.go, e2e/args_test.go, pkg/deployment/external_args.go
=> feat: Allow to load args from files

cmd/kluctl/commands/cmd_list_images.go
=> feat: Allow to pass --offline-kuberntes to list-images

cmd/kluctl/args/project.go, cmd/kluctl/commands/utils.go, pkg/git/git-url/url.go, pkg/git/repocache/cache.go, pkg/kluctl_project/targets.go, pkg/kluctl_project/targets_test.go, pkg/status/status.go, pkg/types/url.go, pkg/vars/vars_loader_test.go
This will allow the user to override any external git repo with a local one.
=> feat: Allow overriding of external git repos with local repos

cmd/kluctl/args/project.go, cmd/kluctl/commands/utils.go, e2e/contexts_test.go, e2e/no_target_test.go, pkg/kluctl_project/project.go, pkg/kluctl_project/target_context.go, pkg/kluctl_project/targets.go
This PR improves the support for deployments without target definitions.
See commits for more details.
=> feat: Better support for no-target runs

e2e/hooks_test.go
Add some debugging logs to flaky e2e tests.
=> tests: Add some log outputs to debug hook tests flakiness

pkg/validation/validation.go
This allows to ignore an object while validation is running.
=> feat: Implement kluctl.io/validate-ignore annotation

e2e/args_test.go, e2e/contexts_test.go, e2e/default_clusters.go, e2e/deploy_test.go, e2e/flux_test.go, e2e/hooks_test.go, e2e/inclusion_test.go, e2e/no_target_test.go, e2e/seal_test.go, e2e/test_resources/kluctl-deployment.yaml, e2e/test_resources/resources.go, e2e/utils.go, go.mod, go.sum, internal/test-utils/envtest_cluster.go, internal/test-utils/envtest_cluster_callback.go, pkg/deployment/commands/validate.go, pkg/deployment/utils/apply_utils.go, pkg/validation/validation.go
This PR contains multiple optimizations and speedups for CI/test runs
=> ci: Speedup tests and CI runs

pkg/deployment/commands/deploy.go
This will also output the list orphan objects before asking if the deployment should be performed.
=> feat: Also print orphan objects when showing diff before deploy

cmd/kluctl/commands/cobra_utils.go, e2e/args_test.go, pkg/vars/vars_loader.go, pkg/vars/vars_loader_test.go
=> Multiple fixes in regard to environment value handling

CODE_OF_CONDUCT.md, CONTRIBUTING.md, DEVELOPMENT.md, README.md
This PR adds community related docs and updates the README.md
=> Add community related docs

pkg/deployment/commands/poke_images.go
`poke-images` was ignoring `initContainers`, which is fixed by this PR.
=> fix: Also take initContainers into account in poke-images

docs/reference/deployments/readiness.md
That same section is already inside hooks.md
=> docs: Remove redundant section from readiness.md

go.mod, go.sum
See https://github.com/xanzy/ssh-agent/pull/11
Fixes #94 
=> fix: Upgrade github.com/xanzy/ssh-agent to current master to fix crash

pkg/status/multiline/multiline.go
This fixes continues printing of new lines when multiline status is shown.
=> fix: Fix clearing of multiline status lines

docs/get-started.md, docs/reference/deployments/README.md, docs/reference/kluctl-project/README.md, e2e/args_test.go, e2e/contexts_test.go, e2e/deployment_items_test.go, e2e/flux_test.go, e2e/hooks_test.go, e2e/inclusion_test.go, e2e/no_target_test.go, e2e/project.go, e2e/seal_test.go, e2e/sops_test.go, pkg/deployment/commands/delete.go, pkg/deployment/deployment_item.go, pkg/deployment/deployment_project.go, pkg/deployment/external_args.go, pkg/deployment/utils/remote_objects_utils.go, pkg/kluctl_project/target_context.go, pkg/types/deployment.go, pkg/types/kluctl_project.go
This PR implements support for deployments/diffs of plain Kustomize deployments.
=> feat: Allow to use kluctl with plain kustomize deployments

pkg/deployment/helm_chart.go
=> fix: Fix "invalid cross-device link" errors when pulling charts inside docker

cmd/kluctl/commands/cmd_helm_pull.go, cmd/kluctl/commands/cmd_helm_update.go, pkg/utils/limited_routine.go
Recent test failures showed a race condition in regard to `errs`.
=> fix: Fix race condition due to use of GoLimitedMultiError

pkg/deployment/utils/apply_utils.go
The ApplyUtil only tracks applied objects of the current deployment item but not objects that were previously applied by other instances. This causes namespaces to be considered "non-existent" when not created in the same item. This is fixed by globally tracking created namespaces.
Fixes #146 
=> fix: Fix simulation of dryRun creation into fresh namespaces

pkg/deployment/deployment_item.go, pkg/deployment/shared_context.go, pkg/kluctl_project/load.go, pkg/kluctl_project/project.go, pkg/kluctl_project/project_load.go, pkg/kluctl_project/target_context.go, pkg/sops/sops_decryptor.go, pkg/sops/utils.go, pkg/vars/vars_loader.go, pkg/vars/vars_loader_test.go, pkg/yaml/yaml.go
This is the preparation for SOPS support in the flux-kluctl-controller
=> feat: Allow to pass SOPS decrypter from outside

pkg/registries/registries.go
This should fix flakiness in Windows CI tests.
=> fix: Use locked files to write/read registry cache files

e2e/sops_test.go, pkg/deployment/deployment_item.go, pkg/deployment/helm_chart.go, pkg/sops/utils.go, pkg/vars/sops_test_resources/README.md, pkg/vars/sops_test_resources/helm-values.yaml
This adds support for SOPS encrypted helm-files.yaml
Fixes #123 
=> feat: Support SOPS in helm-files.yaml

cmd/kluctl/commands/cmd_helm_pull.go, cmd/kluctl/commands/cmd_helm_update.go, docs/reference/deployments/helm.md, e2e/helm_test.go, e2e/test-utils/project.go, pkg/deployment/helm_chart.go, pkg/types/helm_chart.go
This adds support for `updateConstraints` in `helm-chart.yaml`.
Fixes #127
=> feat: Support specifying constraints when updating helm charts

docs/reference/deployments/annotations/all-resources.md, pkg/diff/managed_fields.go, pkg/diff/managed_fields_test.go
This implements the `kluctl.io/ignore-conflicts` and `kluctl.io/ignore-conflics-field` annotations. It also adds tests for conflict resolution.
Fixes #126
=> feat: Allow to ignore SSA conflicts on a per-object basis

pkg/deployment/deployment_item.go, pkg/deployment/utils/delete_utils.go, pkg/diff/normalize.go
This will make Kluctl respect `helm.sh/resource-policy: true`.
=> feat: Add compatibility code for helm.sh/resource-policy annotation

cmd/kluctl/commands/cmd_render.go, docs/reference/commands/render.md, docs/reference/deployments/deployment-yml.md, pkg/deployment/commands/poke_images.go, pkg/deployment/commands/validate.go, pkg/deployment/deployment_collection.go, pkg/deployment/deployment_item.go, pkg/deployment/utils/apply_utils.go, pkg/deployment/utils/diff_utils.go
This PR adds support for inclusion flags on `kluctl render`.
Fixes #147
=> feat: Allow inclusion flags on render command

docs/reference/templating/variable-sources.md, pkg/types/vars_source.go, pkg/vars/aws/fake_clientfactory.go, pkg/vars/vars_loader.go, pkg/vars/vars_loader_http.go, pkg/vars/vars_loader_test.go, pkg/vars/vault/secrets.go
This allows to gracefully ignore not found variable sources
Fixes #149
=> feat: Allow to ignore missing variable sources

pkg/registries/registries.go
Fixes a crash that was observes in e2e tests.
=> fix: Fix potential crash in readCachedResponse

cmd/kluctl/args/misc.go, cmd/kluctl/commands/cmd_delete.go, cmd/kluctl/commands/cmd_deploy.go, cmd/kluctl/commands/cmd_diff.go, cmd/kluctl/commands/cmd_poke_images.go, cmd/kluctl/commands/cmd_prune.go, cmd/kluctl/commands/command_result.go, docs/reference/commands/delete.md, docs/reference/commands/deploy.md, docs/reference/commands/diff.md, docs/reference/commands/poke-images.md, docs/reference/commands/prune.md, e2e/obfuscate_test.go, e2e/seal_test.go, e2e/utils.go, e2e/utils_resources.go, pkg/diff/diff.go, pkg/diff/obfuscate.go
This will obfuscate (replace values with `*****`) Secrets.
Fixes #124 
=> feat: Feat obfuscate diffs of Secrets

.goreleaser.yaml, cmd/kluctl/commands/cmd_version.go, cmd/kluctl/commands/cobra_utils.go
=> fix: Fix completion help, installation and version output

pkg/yaml/yaml_test.go
In order to increase the test coverage, this PR adds tests for the yaml pkg.
=> tests: Add unit tests for the yaml pkg

pkg/repocache/cache.go
findCommit was not able to detect `refs/tags/my-tag` and thus failed to find the commit.
=> fix: findCommit did not account for tags

pkg/vars/aws/arn.go, pkg/vars/aws/fake_clientfactory.go, pkg/vars/aws/secrets_manager.go
This PR introduces the use of the official AWS lib for ARN parsing.
=> Migrate ARN parsing to official AWS library

docs/reference/templating/variable-sources.md, pkg/types/vars_source.go, pkg/vars/vars_loader.go, pkg/vars/vars_loader_http.go, pkg/vars/vars_loader_test.go
This will be useful when loading "default" variables that should not override existing ones.
=> feat: Allow to load variables without overriding previously loaded variables

pkg/git/auth/ssh_auth_provider.go
=> fix: Respect IdentityAgent from SSH config

pkg/types/git_project.go, pkg/types/validators_test.go
Closes: https://github.com/kluctl/kluctl/issues/269
improvement in git subDir path validation
=> fix: Fix subDir path validation

docs/reference/deployments/deployment-yml.md, docs/reference/templating/variable-sources.md, e2e/utils_resources.go, e2e/when_test.go, pkg/deployment/deployment_collection.go, pkg/deployment/deployment_project.go, pkg/kluctl_jinja2/conditionals.go, pkg/types/deployment.go, pkg/types/vars_source.go, pkg/vars/vars_loader.go, pkg/vars/vars_loader_test.go
This PR implements conditionals via `when` for deployment items and variable sources. This allows to use much less templating inside deployment projects.
=> feat: Implement conditional deployment items and variable sources

pkg/utils/uo/nested_fields.go
=> fix: Fix RemoveNestedField to properly delete slice elements

docs/reference/deployments/annotations/all-resources.md, docs/reference/deployments/deployment-yml.md, pkg/deployment/deployment_project.go, pkg/deployment/utils/diff_utils.go, pkg/diff/normalize.go, pkg/diff/normalize_test.go, pkg/types/deployment.go, pkg/utils/uo/jsonpath.go, pkg/utils/uo/nested_fields.go
This PR adds support for regex based pathes in ignoreForDiff.
It also fixes `--ignore-tags` in the `diff` command.
=> feat: Implement regex based ignoreForDiff

cmd/kluctl/commands/root.go, pkg/deployment/images.go, pkg/deployment/utils/diff_utils_test.go, pkg/git/git-url/url.go, pkg/git/test_git_server.go, pkg/git/utils.go, pkg/repocache/cache.go, pkg/types/command_result.go, pkg/types/deployment.go, pkg/types/git_project.go, pkg/types/helm_chart.go, pkg/types/k8s/ref.go, pkg/types/kluctl_project.go, pkg/types/target_config.go, pkg/types/url.go, pkg/types/vars_source.go, pkg/utils/uo/nested_fields.go, pkg/utils/uo/uo.go, pkg/vars/vars_loader_test.go, pkg/vars/vars_test.go, pkg/yaml/yaml.go, pkg/yaml/yaml_test.go
This aligns with how the k8s ecosystem is doing it everywhere, which makes a few things easier for us in the future.
=> feat: Switch to using json tags instead of yaml tags

docs/reference/deployments/deployment-yml.md
See commit.
Fixes https://github.com/kluctl/flux-kluctl-controller/issues/96
=> docs: Update commonLabels documentation to not mention the use for deletion/pruning

docs/reference/deployments/kustomize.md
Adds and example of how you might want to use Kustomize integration
=> docs: Add example for Kustomize integration

cmd/kluctl/commands/cmd_delete.go, docs/reference/commands/delete.md, docs/reference/deployments/deployment-yml.md, pkg/deployment/deployment_item.go, pkg/deployment/deployment_project.go, pkg/types/deployment.go
This PR implements `commonAnnotations` the same way as `commonLabels` are implemented.
Fixes #423
=> feat: Implement commonAnnotations

docs/reference/deployments/deployment-yml.md, pkg/types/deployment.go
This adds documentation for `deleteObjects`, which actually already exists since more than a year.
=> docs: Add docs for deleteObjects

docs/reference/templating/variable-sources.md, pkg/types/vars_source.go, pkg/utils/uo/jsonpath.go, pkg/vars/vars_loader.go, pkg/vars/vars_loader_test.go
This allows to load non-dict values from ConfigMaps and Secrets.
Fixes #351
=> feat: Implement targetPath in configMap/secret vars sources

pkg/yaml/yaml.go
This fixes issues with new-lines being lost in ConfigMaps.
=> fix: Use apimachinery YAMLReader utils to parsy multi-doc YAML

.github/workflows/tests.yml, Makefile
=> ci: Fix windows tests

cmd/kluctl/args/project.go, cmd/kluctl/commands/cmd_controller.go, cmd/kluctl/commands/root.go, cmd/kluctl/commands/utils.go, docs/reference/commands/common-arguments.md, e2e/gitops_test.go, e2e/results_test.go, pkg/controllers/kluctldeployment_controller_setup.go
This is still a beta feature and thus shouldn't be enabled by default.
=> feat: Disable writing of command results by default

pkg/k8s/k8s_cluster.go
=> fix: Don't copy mutex by value

cmd/kluctl/commands/cmd_controller.go, config/rbac/role.yaml, pkg/controllers/kluctl_project.go, pkg/controllers/kluctldeployment_controller.go, pkg/utils/uo/nested_fields.go
This will be part of the migration path from the legacy flux-kluctl-controller to the new gitops controller. Documentation will follow.
=> feat: Implement migration checks for legacy flux-kluctl-controller

config/manager/manager.yaml, install/controller/controller/kustomization.yaml, install/controller/controller/manager.yaml, pkg/controllers/kluctl_project.go, pkg/results/result-store-secrets.go, pkg/types/git_url.go
=> fix: Multiple fixes for the controller

config/manager/manager.yaml, install/controller/controller/manager.yaml
=> fix: Give controller more CPU limits

cmd/kluctl/commands/cmd_delete.go, cmd/kluctl/commands/cmd_prune.go, pkg/controllers/kluctl_project.go, pkg/deployment/commands/delete.go, pkg/deployment/commands/prune.go
Otherwise the controller will block too much.
=> fix: Don't wait for deletion when performed by the controller

pkg/controllers/kluctldeployment_controller.go
Otherwise we might patch unintended changes.
=> fix: Create patch object right before the actual modification

pkg/controllers/kluctldeployment_controller.go
Otherwise the retrieved object gets "lost".
=> fix: Directly use unstructured.Unstructured when getting legacy KD object

Makefile
=> build: Multiple fixes to docs generation and checks

Dockerfile, hack/prepare-release.sh, install/controller/controller/kustomization.yaml, pkg/git/auth/list_auth_provider.go
Please check the individual commits.
=> fix: Multiple fixes for the Kluctl controller

.github/workflows/nightly.yml, .goreleaser.yaml
This introduces nightly/devel builds and pre-releases, leveraging goreleasers nightly features.
=> ci: Add nightly/devel builds for main branch

.github/workflows/nightly.yml
Copy-paste error resulted in wrong name for the new nightly release workflow.
=> ci: Fix name of nightly release workflow

.goreleaser.yaml
Otherwise the releases look quite strange (vdevel).
=> ci: Use next version number in devel version

.github/workflows/nightly.yml, .goreleaser.yaml
This fixes missing versions in nightlies. It also adds an action to set draft=false for nightlies.
=> ci: Fix missing version in nightlies and mark as non-draft

.goreleaser.yaml
=> ci: Fix docker tags and add header to nightly releases

README.md
The version badge will otherwise always show `devel`.
=> docs: Don't include pre-releases in version badge

Dockerfile
wolfi-base already has this installed.
=> chore: Remove unneeded ca-certificates installation from Dockerfile

config/manager/manager.yaml, install/controller/.kluctl.yaml, install/controller/controller/kustomization.yaml, install/controller/controller/manager.yaml
=> feat: Multiple improvements to controller deployment

e2e/diff_name_test.go, e2e/utils_resources.go, pkg/deployment/commands/utils.go, pkg/deployment/utils/diff_utils.go, pkg/deployment/utils/diff_utils_test.go
This stopped working while introducing the new command results.
=> fix: Honor kluctl.io/diff-name again

.github/workflows/tests.yml
Release branches should also run the tests workflow.
=> ci: Also run tests workflow on releaser branch

api/v1beta1/kluctldeployment_types.go, config/crd/bases/gitops.kluctl.io_kluctldeployments.yaml, install/controller/controller/crd.yaml
It was empty due to an outdated field name.
=> fix: Fix DEPLOYED printer column

hack/prepare-release.sh, install/webui/webui/deployment.yaml
=> fix: Fix snapshot detection and version replacement via prepare-release.sh

cmd/kluctl/commands/cmd_controller_install.go, install/controller/.kluctl.yaml, install/controller/controller/kustomization.yaml
=> fix: Rename controller_version to kluctl_version and fix snapshot detection

pkg/webui/ui/.gitattributes
*.map files are also affected with same problem as described in #586
=> fix: Also treat *.map as eol=lf

cmd/kluctl/commands/cmd_webui.go, pkg/webui/events.go, pkg/webui/server.go
=> feat: Fix nextSeq handling and implement --host flag

cmd/kluctl/commands/cmd_helm_update.go, pkg/deployment/commands/result_utils.go, pkg/git/utils.go
This is a workaround inspired by https://github.com/mooltiverse/nyx/issues/130#issuecomment-1399572420.
Fixes #602
=> fix: Introduce workaround for incorrect CRLF handling in git status

docs/reference/templating/variable-sources.md
This updates the documentation to describe how to do #477.
Fixes #477
=> docs: Document how values vars sources can use vars previously defined

install/controller/.kluctl.yaml, install/controller/controller/kustomization.yaml, install/webui/.kluctl.yaml, install/webui/webui/deployment.yaml
Update this with the latest released patch version.
=> chore: Update controller/webui versions to v2.20.6

docs/installation.md
=> docs: Also update installation instructions with new version

pkg/controllers/kluctl_project.go, pkg/controllers/kluctldeployment_controller.go, pkg/git/utils.go, pkg/repocache/cache.go
Extracting it from the checked out repo resulted in the loss of the ref as we're checking out by commit.
=> fix: Properly collect git checkout info

pkg/git/mirrored_repo.go
This is required because go-git currently does not support multi_ack/multi_ack_detailed.
See https://github.com/go-git/go-git/issues/64 and https://github.com/go-git/go-git/pull/613.
=> fix: Add workaround to support Azure DevOps and other protocol-v2 git repos

api/v1beta1/util_types.go, config/crd/bases/gitops.kluctl.io_kluctldeployments.yaml, install/controller/controller/crd.yaml
This got into the new controller by accident. It's a leftover from the legacy flux-kluctl-controller.
=> fix: Remove 'never' from allowed values for SafeDuration

Dockerfile, install/controller/.kluctl.yaml, install/controller/controller/kustomization.yaml, install/webui/.kluctl.yaml, install/webui/webui/deployment.yaml
=> fix: Fix preview-run (missing wolfi digest) and allow to override controller resources

pkg/webui/ui/src/components/ScrollingTextLine.tsx, pkg/webui/ui/src/components/targets-view/Card.tsx, pkg/webui/ui/src/components/targets-view/ExpandedCardsView.tsx, pkg/webui/ui/src/components/targets-view/TargetsView.tsx
Added scrolling text animation for long headings.
=> feat: Added scrolling text animation for long headings.

pkg/webui/ui/src/components/App.tsx, pkg/webui/ui/src/components/result-view/CommandResultView.tsx, pkg/webui/ui/src/components/targets-view/CommandResultItem.tsx, pkg/webui/ui/src/components/targets-view/ExpandedCardsView.tsx, pkg/webui/ui/src/components/targets-view/TargetsView.tsx
Load card data only for the currently visible card.
=> Load cards one by one.

pkg/webui/ui/src/components/targets-view/TargetsView.tsx
Change the mouse cursor when hovering over expandable cards.
=> Change mouse cursor when hovering over expandable cards.

install/webui/webui/webui-rbac.yaml, pkg/controllers/kluctl_project.go, pkg/controllers/kluctldeployment_controller.go, pkg/controllers/kluctldeployment_controller_utils.go, pkg/k8s/k8s_cluster.go, pkg/k8s/utils.go, pkg/results/result-store-secrets.go, pkg/results/result-store.go, pkg/results/results-collector.go, pkg/webui/events.go, pkg/webui/server.go, pkg/webui/ui/src/api.tsx, pkg/webui/ui/src/components/ActionsMenu.tsx, pkg/webui/ui/src/components/App.tsx, pkg/webui/ui/src/components/FilterBar.tsx, pkg/webui/ui/src/components/LeftDrawer.tsx, pkg/webui/ui/src/components/result-view/CommandResultTree.tsx, pkg/webui/ui/src/components/result-view/CommandResultView.tsx, pkg/webui/ui/src/components/targets-view/TargetItem.tsx, pkg/webui/ui/src/project-summaries.ts
See individual commits. Most important improvement is the consideration of KluctlDeployment objects in the targets view.
=> feat: Multiple improvements to the webui

pkg/webui/auth.go, pkg/webui/auth_oidc.go, pkg/webui/ui/src/setupProxy.js
This ensures that token expiration is honored.
=> fix: Store full token in session and re-validate it

go.mod, go.sum, pkg/results/result-store-secrets.go, pkg/results/result-store.go, pkg/results/results-collector.go, pkg/webui/events.go, pkg/webui/server.go, pkg/webui/ui/src/api.tsx, pkg/webui/ui/src/components/App.tsx
The reason for going with long-polling does not exist anymore, so we can go back to websockets now.
=> feat: Switch back to websockets for events

install/webui/webui/deployment.yaml
=> fix: Set args to [] for webui deployment

docs/reference/templating/variable-sources.md
Missed the docs update before.
=> docs: Add mention of "sensitive" field for vars sources

cmd/kluctl/commands/root.go, pkg/webui/auth.go, pkg/webui/auth_oidc.go, pkg/webui/ui/src/components/targets-view/TargetItem.tsx
This PR also contains a few fixes, see individual commits.
=> feat: Implement oidc/oauth2 token refresh

pkg/webui/auth.go, pkg/webui/server.go, pkg/webui/server_logs.go
=> fix: Fix crash when starting webui from command line without args

docs/reference/commands/webui-run.md, go.mod, go.sum, pkg/vars/vars_loader.go
This pulls in https://github.com/kluctl/go-jinja2/commit/ac74568e03811717901eda7cb05a22937be1bf48.
=> fix: Upgrade to latest version of go-jinja2 to fix rendering of relative templates

pkg/webui/ui/src/components/App.tsx, pkg/webui/ui/src/components/Login.tsx, pkg/webui/ui/src/components/Router.tsx, pkg/webui/ui/src/components/target-view/ManualApproveButton.tsx, pkg/webui/ui/src/components/target-view/ReconcilingIcon.tsx, pkg/webui/ui/src/components/target-view/TargetsView.tsx, pkg/webui/ui/src/project-summaries.ts
=> feat: Multiple improvements to webui

api/v1beta1/kluctldeployment_types.go, cmd/kluctl/args/project.go, config/crd/bases/gitops.kluctl.io_kluctldeployments.yaml, docs/gitops/api/kluctl-controller.md, docs/kluctl/commands/common-arguments.md, install/controller/controller/crd.yaml, pkg/controllers/kluctl_project.go, pkg/controllers/kluctldeployment_controller.go, pkg/controllers/predicates.go, pkg/types/result/command_result.go, pkg/types/result/command_result_summary.go, pkg/types/result/drift_detection_result.go, pkg/types/result/validate_result.go, pkg/webui/server.go, pkg/webui/ui/src/api.tsx, pkg/webui/ui/src/components/command-result/nodes/CommandResultNode.tsx, pkg/webui/ui/src/components/target-list-view/TargetsListView.tsx, pkg/webui/ui/src/components/target-view/ReconcilingIcon.tsx, pkg/webui/ui/src/components/target-view/TargetActionMenu.tsx, pkg/webui/ui/src/models.ts
=> feat: Implement prune requests

docs/webui/README.md
=> docs: Fix links to webui screenshots

docs/webui/installation.md, docs/webui/oidc-azure-ad.md, docs/webui/running-locally.md, hack/prepare-release.sh, install/webui/webui/webui-rbac.yaml, pkg/controllers/kluctldeployment_controller.go, pkg/k8s/utils.go, pkg/webui/auth.go, pkg/webui/auth_oidc.go
=> feat: Auto-generate static credentials and auth secret if non-existent

cmd/kluctl/commands/cmd_controller_install.go, pkg/deployment/commands/result_utils.go, pkg/webui/ui/src/components/target-cards-view/ProjectCard.tsx
=> fix: Honor --yes in "controller install" and fix git info error

cmd/kluctl/commands/command_result.go, config/manager/manager.yaml, docs/gitops/spec/v1beta1/kluctldeployment.md, install/controller/controller/manager.yaml, install/webui/webui/deployment.yaml, pkg/webui/ui/src/components/LeftDrawer.tsx, pkg/webui/ui/src/components/card/Card.tsx, pkg/webui/ui/src/components/card/CardTabs.tsx, pkg/webui/ui/src/components/target-cards-view/TargetCardsView.tsx
=> A few minor fixes/changes

cmd/kluctl/commands/cmd_delete.go, docs/kluctl/commands/delete.md
=> feat: Add --no-wait flag to delete command

docs/kluctl/deployments/annotations/all-resources.md, docs/kluctl/deployments/annotations/hooks.md, docs/kluctl/deployments/annotations/kustomization.md, pkg/deployment/commands/validate.go, pkg/deployment/deployment_item.go, pkg/deployment/utils/apply_utils.go, pkg/deployment/utils/delete_utils.go, pkg/deployment/utils/hooks_util.go, pkg/diff/managed_fields.go, pkg/diff/normalize.go, pkg/utils/uo/k8s_fields.go, pkg/validation/validation.go
=> docs: Update docs about new wait-readiness behaviour

cmd/kluctl/commands/cmd_delete.go, cmd/kluctl/commands/cmd_deploy.go, cmd/kluctl/commands/cmd_diff.go, cmd/kluctl/commands/cmd_poke_images.go, cmd/kluctl/commands/cmd_prune.go, cmd/kluctl/commands/cmd_validate.go, pkg/controllers/kluctl_project.go, pkg/controllers/kluctldeployment_controller.go, pkg/deployment/commands/delete.go, pkg/deployment/commands/deploy.go, pkg/deployment/commands/diff.go, pkg/deployment/commands/poke_images.go, pkg/deployment/commands/prune.go, pkg/deployment/commands/result_utils.go, pkg/deployment/commands/validate.go
=> fix: Fix crash and missing results when timeouts happen

docs/kluctl/deployments/annotations/all-resources.md, docs/kluctl/deployments/readiness.md, e2e/hooks_test.go, e2e/utils.go, pkg/deployment/commands/validate.go, pkg/deployment/deployment_item.go, pkg/deployment/utils/apply_utils.go, pkg/deployment/utils/delete_utils.go, pkg/deployment/utils/hooks_util.go, pkg/diff/managed_fields.go, pkg/diff/normalize.go, pkg/utils/uo/k8s_fields.go, pkg/validation/validation.go
This fixes a bug that slipped through due to a refactoring of annotation parsing. The bug caused hooks to not wait anymore.
=> fix: Fix broken waiting for hooks

.github/dependabot.yml
Let's try to reduce the number of dependabot PRs with this.
=> ci: Group aws-sdk dependabot updates

e2e/helm_test.go, e2e/test-utils/test-helm-chart/templates/configmap.yaml, pkg/helm/helm_release.go
This allows to use Helm's lookup functions, which is finally possible since due to https://github.com/helm/helm/pull/9426 being merged and released :tada:
Fixes #707
=> feat: Allow Helm lookups

go.mod, go.sum
https://github.com/go-git/go-git/issues/181 was the reason behind the slowness of #894. This was fixed in https://github.com/go-git/go-git/pull/825 which is however not released yet. This PR uses the latest master commit to bring the fix in.
Fixes #894
=> fix: Update go-git to current master to fix slow git status

.github/workflows/tests.yml, .goreleaser.yaml, Dockerfile
This should avoid situation like #952 to re-appear.
=> fix: Simplify wolfi-base updates and test if the docker image still works

docs/gitops/README.md, docs/kluctl/deployments/deployment-yml.md, docs/kluctl/get-started.md, docs/kluctl/templating/README.md, docs/kluctl/templating/filters.md, docs/kluctl/templating/functions.md
This just updates a few links.
=> docs: Point to 3.1.x docs for Jinja2

docs/kluctl/commands/gitops-diff.md, docs/kluctl/templating/variable-sources.md
=> docs: A few docs updates/fixes

cmd/kluctl/commands/command_result.go, cmd/kluctl/commands/utils.go, e2e/remote_objects_permission_test.go, pkg/deployment/commands/result_utils.go, pkg/deployment/utils/apply_utils.go, pkg/deployment/utils/remote_objects_utils.go, pkg/k8s/utils.go, pkg/results/result-store-secrets.go
This PR contains multiple fixes so that users with very limited permissions can still Kluctl.
Fixes the issue described in https://github.com/kluctl/kluctl/discussions/984.
Really fixes https://github.com/kluctl/kluctl/issues/237, which was only partially fixed before via https://github.com/kluctl/kluctl/pull/247.
=> fix: Fix issues for users that only have permissions for one namespace

Makefile, config/crd/bases/gitops.kluctl.io_kluctldeployments.yaml, install/controller/controller/crd.yaml
This fixes crashes with Go v1.22. Thanks @Bharadwajshivam28 for reporting the crash :bug:
=> fix: Upgrade controller-gen to v0.14.0

cmd/kluctl/commands/cmd_controller_install.go, cmd/kluctl/commands/cmd_deploy.go, cmd/kluctl/commands/cmd_diff.go, cmd/kluctl/commands/cmd_prune.go, cmd/kluctl/commands/utils.go, docs/kluctl/commands/deploy.md, docs/kluctl/commands/diff.md, docs/kluctl/commands/prune.md, e2e/controller_install_test.go, e2e/crds_test.go, e2e/discriminator_test.go, e2e/utils.go, pkg/kluctl_project/target-context/target_context.go
=> feat: Implement --discriminator and make "controller install" also set a discriminator

e2e/gitops_errors_test.go, e2e/gitops_git_include_test.go, e2e/images_test.go, e2e/seal_test.go, pkg/deployment/deployment_project.go, pkg/diff/normalize_test.go, pkg/sourceoverride/proxyclient_cli.go, pkg/sourceoverride/proxyserver.go, pkg/types/validators_test.go, pkg/types/vars_source.go, pkg/utils/utils.go, pkg/vars/vars_loader_test.go
=> fix: Use struct tag to mark fields that should be exclusive

cmd/kluctl/commands/cmd_oci_push.go, pkg/oci/auth/aws/auth.go, pkg/oci/auth/aws/auth_test.go, pkg/oci/client/build.go, pkg/oci/client/build_test.go, pkg/oci/client/diff.go, pkg/oci/client/diff_test.go, pkg/oci/client/internal/fs/LICENSE, pkg/oci/client/internal/fs/fs.go, pkg/oci/client/internal/fs/rename.go, pkg/oci/client/internal/fs/rename_windows.go, pkg/oci/client/login.go, pkg/oci/client/login_test.go, pkg/oci/client/pull.go, pkg/oci/client/pull_test.go, pkg/oci/client/push.go, pkg/oci/client/push_pull_test.go, pkg/oci/client/suite_test.go, pkg/oci/globals.go
This fixes #1046 and also syncs the pkg/oci code with the latest flux/pkg/oci source. 
Fixes #1046
=> fix: Remove source file in renameWithFallback

go.mod, go.sum
Master now includes the fix for unknown index extensions.
=> chore: Update go-git to latest master

Dockerfile
=> fix: Add missing gpg and gpg-agent packages to docker image

e2e/diff_name_test.go, e2e/git_info_test.go, e2e/test_project/project.go, pkg/git/git_info.go
=> fix: Don't fail when the git repo has no commits

docs/kluctl/deployments/annotations/hooks.md, docs/kluctl/deployments/hooks.md
- Add reference to `annotation/hooks` page from the primary `hooks` documentation page
- Specify that hooks are executed in ascending order of hook-weight
=> docs: clarify hook annotation docs

pkg/deployment/utils/remote_objects_utils.go, pkg/k8s/k8s_cluster.go
=> fix: Ignore a few warnings happening while discovering orphans

hack/prepare-release.sh, install/controller/files.json
`install/controller/files.json` was not updated properly in the last release. This will fix it in future releases.
=> fix: Also re-run generate-install in prepare-release.sh

pkg/deployment/utils/apply_utils.go, pkg/k8s/crd_cache.go, pkg/utils/go_helper.go
=> fix: Fix detection of CRD added in the background

.github/dependabot.yml
This allows auto-updates of wolfi-base.
=> ci: Add docker package-ecosystem to dependabot config

docs/kluctl/deployments/deployment-yml.md, docs/kluctl/kluctl-libraries/README.md
The git urls were wrong, this fixes them.
=> docs: Fix git+ssh url examples

docs/gitops/spec/v1beta1/kluctldeployment.md
Missed to document this field.
=> docs: Add missing spec.timeout to kluctldeployment.md

e2e/remote_objects_permission_test.go, pkg/deployment/utils/remote_objects_utils.go
This will allow orphan object detection to work in many cases even if
permissions are limited to just single namespaces.
Fixes #1215
=> feat: Implement per-namespace list in RemoteObjectUtils in case of permission errors

pkg/deployment/deployment_project.go
These tags would otherwise cause follow up errors.
=> fix: Do not allow . and .. as default tags

docs/gitops/metrics/v1beta1/kluctldeployment_controller.md, pkg/controllers/kluctldeployment_controller.go, pkg/controllers/kluctldeployment_controller_status.go, pkg/controllers/metrics/kluctldeployment_controller.go
Adding new metric Last deploy start time for kluctl deployments.
Fixes #1294
=> feat(metrics): add last deploy start time metric

.github/workflows/nightly.yml, .github/workflows/preview-proxy.yml, .github/workflows/preview-run.yml, .github/workflows/release.yml, .github/workflows/tests.yml, cmd/kluctl/commands/cmd_helm_update.go, go.mod, pkg/clouds/gcp/fake_clientfactory.go, pkg/controllers/kluctldeployment_controller.go, pkg/deployment/utils/errors_holder.go, pkg/sops/decryptor/decryptor.go
Updating go to 1.24. This should hopefully also fix dependabot issues.
=> chore: Upgrade go versiom to 1.24

e2e/crds_test.go, e2e/readiness_test.go
=> fix: Fix flakiness of a few tests

e2e/validate_test.go
Need to debug a few flakes happening irregularly.
=> tests: Add some logging to allow fixing of flakes

docs/kluctl/deployments/annotations/all-resources.md, e2e/ignore_annotation_test.go, e2e/test_project/project.go, pkg/deployment/deployment_item.go, pkg/k8s/utils.go
This implements the kluct.io/ignore annotation which can be used to ignore a resource.
=> feat: Implement kluct.io/ignore annotation
