kluctl/deployment/hooks_util.py

kluctl failed because ref is a mandatory parameter but wasn't passed when adding an api warning because of an unsupported helm hook.

fix: add missing object ref for api warning

---

kluctl/deployment/deployment_project.py

If a kustomizeDir is mistakenly configured as an include, the error message "deployment.yml not found" is not very helpful. I added two things: 
- If a kustomization.yml was found instead of a deployment.yml, the user gets a helpful error message with a hint to the solution
- In any other case, the complete path to the missing deployment.yml will be printed to help the user find the problematic include

feat: add more informative error message when deployment.yml is missing

---

.github/ISSUE_TEMPLATE/FEATURE.yml

Signed-off-by: Aljoscha Pörtner <aljoscha.poertner@posteo.de>
This PR adds the `label` key in front of each options entry.

chore: put label in front of options in feature request

---

pkg/deployment/commands/seal.go

When creating a secrets project I have forgotten the configuration for `outputPattern and location of stored sealed secrets`.
When I try to seal against the cluster I get a nullpointer exception instead of the error message 
```bash
➜  simple-with-secrets git:(main) kluctl seal -t simple
INFO[0001] Sealing for target simple                    
INFO[0002] Rendering templates and Helm charts          
WARN[0002] Failed to retrieve public certificate from sealed-secrets-controller, re-trying with bootstrap secret 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x183da22]
goroutine 1 [running]: …
```

fix: runtime error on seal command when missing SealedSecret (nil)

---

cmd/kluctl/commands/cmd_list_images.go
pkg/deployment/images.go

In large deployment projects we use the `list-images` together with the `fixed-image` feature for our production environment to bring all images from UAT to a fixed version on the PROD environment. We then place the fixed-image.yml file in a git repository. Currently the result of `list-images` is unsorted, which makes it difficult to review during an update. Therefore kluctl should have the option to sort the output.
```bash
kluctl list-images --simple --sort -t simple
```

feat: add sorted output for list images

---

cmd/kluctl/commands/root.go

This fixes swallowing of log messages on Windows (and probably on other OSes as well)

fix: Use original stderr file for simple status handler

---

pkg/deployment/deployment_item.go

fix: Skip postprocessCRDs in case --offline-kubernetes was used

---

pkg/utils/python_scanner/README.md
pkg/utils/python_scanner/scanner.go

This avoids unnecessary warnings being printed in case of invalid escape sequences in regex strings. The parser should actually NOT try to parse these escape sequences as it would lead to invalid regex strings in case a valid escape sequence (e.g. \n) is provided.
Fixes #60

fix: Treat strings as raw strings (no escape sequences handles) in version patterns

---

pkg/kluctl_project/target_context.go
pkg/types/kluctl_project.go
pkg/types/vars_source.go
pkg/vars/vars_loader.go

This removes deprecated "sources" from "secretsSets" and "path" from "vars".

Remove deprecated "sources" from "secretsSets" and "path" from "vars"

---

docs/get-started.md

Fixes the example command where we missed a space

Typo fix on getting started page

---

pkg/diff/managed_fields.go

Otherwise field managers that for example contain "kluctl" somewhere in-between are overwritten as well. Noticed this while working on the flux-kluctl-controller.

fix: Make check for overwritten fields managers more strict

---

e2e/helm_test.go
pkg/deployment/helm_chart.go

Consider Helm credentials when the url matches without a credentialsId being provided.

fix: Also consider helm credentials when no credentialsId is provided

---

cmd/kluctl/args/misc.go
cmd/kluctl/commands/cmd_list_images.go
cmd/kluctl/commands/cmd_render.go
cmd/kluctl/commands/cmd_seal.go
cmd/kluctl/commands/utils.go
docs/reference/commands/list-images.md
docs/reference/commands/render.md
e2e/helm_test.go
e2e/sops_test.go
e2e/test-utils/envtest_cluster.go
e2e/test-utils/test-helm-chart/templates/configmap.yaml
pkg/deployment/deployment_item.go
pkg/deployment/helm_chart.go
pkg/deployment/shared_context.go
pkg/kluctl_project/target_context.go

This allows to specify the Kubernetes version that must be assumed while rendering in offline mode. 
Fixes: #128 

feat: Implement --kubernetes-version to be used with --offline-kubernetes

---

go.mod
go.sum

Upgrade to go-git v5.5.0 introduced a build error when cross-compiling without cgo.

fix: Upgrade github.com/pjbgf/sha1cd to 0.2.3 to fix !cgo compilation

---

pkg/git/test_git_server.go
pkg/vars/vars_loader_test.go

A testing cleanup. 
This pull request replaces `os.MkdirTemp` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete.  This saves us at least 2 lines (error check, and cleanup) on every instance.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := os.MkdirTemp("", "")
assert.NoError(t, err)
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```

test: use `T.TempDir` to create temporary test directory

---

pkg/deployment/deployment_item.go
pkg/types/deployment.go

This removes the already deprecated `templateExcludes` field from deployment projects.

feat: Remove templateExcludes from deployment projects

---

cmd/kluctl/commands/root.go

The help was never shown when Kluctl was called without any arguments.

fix: Show help when kluctl is called without arguments

---

cmd/kluctl/commands/cmd_helm_update.go
pkg/deployment/deployment_item.go
pkg/deployment/shared_context.go
pkg/kluctl_project/project.go
pkg/kluctl_project/project_load.go
pkg/kluctl_project/target_context.go

We should use the .helm-charts dir from the included repository and not from the local one.

fix: Use correct .helm-charts dir when using git includes

---

cmd/kluctl/commands/root.go

This will fix "MISSING" strings in final error messages when templating errors occur.

fix: Don't try to treat final error string as formatted string

---

cmd/kluctl/commands/root.go

GlobalFlags must be passed as pointer as otherwise updates to the flags via `copyViperValuesToCobraCmd` are not reflected into GlobalFlags.
Fixes #225 

fix: Fix globals flags being ignored when specified via env variables

---

cmd/kluctl/commands/command_result.go
e2e/obfuscate_test.go
pkg/diff/obfuscate.go

A secret that was empty before must also be obfuscated. Previously, this was omitted as it did not match the `data.` path prefix.

fix: Also obfuscate secrets when data/stringData was empty before

---

pkg/vars/vars_loader.go
pkg/vars/vars_loader_test.go

The "utils.Exists(path)" check always returned false as it did not take searchDirs into account.
Fixes https://github.com/kluctl/flux-kluctl-controller/issues/64

fix: loadFile should NOT ignore all files

---

pkg/kluctl_project/target_context.go

External args are meant to override target args.
Fixes https://github.com/kluctl/flux-kluctl-controller/issues/30

fix: Merge external args after target args

---

pkg/utils/uo/nested_fields.go

This caused a crash when a resource had things like this included:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: test
labels: # notice that this is empty/nil
annotations:
```

fix: Don't crash when encountering nil maps in SetNestedField

---

Makefile

No need to download our own version of kubebuilder-tools for Windows anymore due to https://github.com/kubernetes-sigs/kubebuilder/issues/3005 being finished.

Revert "chore: Download kubebuilder-tools for windows from kubebuilder-tools-releases-windows repo

---

docs/reference/deployments/deployment-yml.md
e2e/deployment_items_test.go
pkg/deployment/deployment_item.go
pkg/git/test_git_server.go

`onlyRender` was available since a very long time and was working in the past. Somehow the functionality got lost and due to missing e2e tests this was never discovered. This MR fixes all that, including the missing documentation.
Fixes #275

fix: Fix onlyRender to actually not treat the path as deployment item

---

pkg/git/auth/ssh_known_hosts.go

This fixes issues when your ~/.ssh/known_hosts file contains entries with with different key types then the ones that Kluctl would end up using. In that case, Kluctl should ask for confirmation instead of bailing out. If confirmed, Kluctl will add another entry in known_hosts that matches the new key type.

fix: Don't fail known_hosts verification when the key-type doesn't match

---

cmd/kluctl/args/images.go
cmd/kluctl/commands/cmd_check_image_updates.go
cmd/kluctl/commands/utils.go
docs/reference/commands/common-arguments.md
docs/reference/deployments/images.md
docs/reference/kluctl-project/targets/README.md
docs/reference/templating/predefined-variables.md
pkg/deployment/deployment_item.go
pkg/deployment/deployment_project.go
pkg/deployment/images.go
pkg/kluctl_jinja2/ext/images_ext.py
pkg/kluctl_project/target_context.go
pkg/kluctl_project/targets.go

This PR does two things:
1. Allow defining fixed images via a global `images` variable.
2. Deprecate all functionality regarding querying docker registries for latest images. This functionality should be provided outside of Kluctl, e.g. via Renovate.

feat: Allow to define fixed images via variable sources and deprecate registry access

---

cmd/kluctl/commands/cmd_delete.go
cmd/kluctl/commands/cmd_deploy.go
cmd/kluctl/commands/cmd_diff.go
cmd/kluctl/commands/cmd_list_targets.go
cmd/kluctl/commands/cmd_prune.go
cmd/kluctl/commands/cmd_seal.go
cmd/kluctl/commands/cmd_validate.go
cmd/kluctl/commands/completion.go
cmd/kluctl/commands/utils.go
docs/reference/commands/delete.md
docs/reference/kluctl-project/README.md
docs/reference/kluctl-project/targets/README.md
docs/reference/templating/filters.md
e2e/inclusion_test.go
e2e/test-utils/project.go
pkg/deployment/commands/delete.go
pkg/deployment/commands/deploy.go
pkg/deployment/commands/diff.go
pkg/deployment/commands/prune.go
pkg/deployment/commands/validate.go
pkg/deployment/deployment_item.go
pkg/deployment/shared_context.go
pkg/deployment/utils/remote_objects_utils.go
pkg/deployment/utils/remote_objects_utils_test.go
pkg/kluctl_project/project_load.go
pkg/kluctl_project/target_context.go
pkg/kluctl_project/targets.go
pkg/types/kluctl_project.go

This PR implements discriminators on Kluctl project/target level. These are from now on used to identify objects for deletion and pruning. `commonLabels` will now only be used to set labels on all objects but for nothing else.

feat: Implement discriminators to identify deployment objects for pruning and deletion

---

e2e/test-utils/project.go
pkg/kluctl_project/target_context.go

When no target is specified, Kluctl creates a no-name default target. In that case, the target should also use the default discriminator.
Fixes #314 

fix: Use default discriminator for deployments without targets

---

pkg/helm/helm_release.go
pkg/k8s/resources.go

Helm internally adds GroupVersion strings AND GroupVersionKind strings to APIVersions. We must replicate this behavior as otherwise things like `.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress"` will not work.
Fixes a bug reported on Slack. Thanks to @jsaalfeld 

fix: Also add full resource strings to Helm's APIVersions

---

docs/reference/kluctl-project/README.md

The default case had the user to declare `target` and `environment` separately. With this change the user only has to use the `target` and the `environment` will be set accordingly.

docs: change environment args to a working default case

---

pkg/utils/uo/k8s_fields.go
pkg/validation/validation.go

This fixes issues with Deployment objects being marked as ready right after applying changes that would make in non-ready.

fix: Don't consider objects as ready when the observedGeneration != generation

---

cmd/kluctl/commands/utils.go
go.mod
go.sum
pkg/git/auth/git_credentials_file.go
pkg/git/git-url/giturls/LICENSE
pkg/git/git-url/giturls/urls.go
pkg/git/git-url/giturls/urls_test.go
pkg/git/git-url/url.go

This fixes simple overrides like `github.com:my-org/my-repo=/local/path/to/override` (as found in the docs).

fix: Also try to parse repo key without dummy scheme

---

docs/reference/kluctl-project/README.md

update link to `target discriminator` target page

docs: link to target discriminator gives a 404

---

pkg/deployment/utils/hooks_util.go

This fixes an issue with helm.sh/hook and kluctl.io/hook that contain spaces around the comma.

fix: Trim spaces when extracting hook annotations

---

pkg/git/auth/git_credentials_file.go

A user in Slack reported that his .git-credentials file was not honoured anymore. This was due to a regression in the file existence check. This PR fixes this. It also fixes matching of credentials with different usernames.

fix: Fix .git-credentials checking/loading/matching

---

pkg/diff/managed_fields.go
pkg/diff/managed_fields_test.go

When an object has `kluctl.io/force-apply: true` and `kluctl.io/ignore-conflics-field: my.field` set at the same time, the `ignore-conflict` directive should have higher priority.

fix: Honor ignore-conflicts even if force-apply is active for a field

---

Makefile

markdown-link-check 3.11.x is failing with this error:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
/src/markdown-link-check:99
input.opts.config = program.opts().config.trim();
^
TypeError: Cannot read properties of undefined (reading 'trim')
at getInputs (/src/markdown-link-check:99:44)
at main (/src/markdown-link-check:232:20)
Node.js v19.8.1
```

fix: Pin markdown-link-check to 3.10.3 until the latest version gets fixed

---

pkg/utils/uo/jsonpath.go

The dash is actually not a valid character in JSON Path identifiers.

fix: Revert handling - as "simple identifier" when building a json path

---

docs/reference/templating/filters.md
go.mod
go.sum

This upgrades go-jinja2 to the latest main branch to enable the optional prefix_length parameter to the sha256 filter.
Fixes #426

feat: Upgrade go-jinja2 to latest main branch to implement sha256 prefix_length

---

e2e/deployment_items_test.go
go.mod
go.sum
pkg/deployment/deployment_item.go
pkg/vars/vars.go

This PR updates go-jinja2 to get in WithTemplateIgnoreRootDir support and then passes the project source root to RenderDirectory. This will then allow to use .templateignore files outside of deployment items.
Fixes #418

feat: Allow .templateignore files in parent folders

---

pkg/deployment/utils/apply_utils.go
pkg/yaml/validator.go

This will prevent showing many "the server could not find the requested resource" errors when performing dry-runs via
`kluctl diff` or the automatic diff happening before deploy.
Fixes #393

feat: Simulate applying of CRs where the CRD is not applied yet

---

pkg/utils/term/read_line.go

This will at least prevent ESC sequences being interpreted when printing the status line. It's not an optimal solution, but better then repeated execution of ESC sequences.
Fixes #396

fix: Ignore ESC in readLine

---

cmd/kluctl/commands/root.go

A version check while generating completion scripts or while performing completion is clearly not intended.
Fixes #447

fix: Don't perform version check in completion command

---

cmd/kluctl/args/misc.go
cmd/kluctl/commands/cmd_delete.go
cmd/kluctl/commands/cmd_deploy.go
cmd/kluctl/commands/cmd_diff.go
cmd/kluctl/commands/cmd_poke_images.go
cmd/kluctl/commands/cmd_prune.go
cmd/kluctl/commands/command_result.go
docs/reference/commands/delete.md
docs/reference/commands/deploy.md
docs/reference/commands/diff.md
docs/reference/commands/poke-images.md
docs/reference/commands/prune.md

`--short-output` will cause Kluctl to not print detailed changes anymore. Only the names of changed objects are then printed.
Fixes #449

feat: Implement --short-output flag

---

Makefile

This should fix e2e tests on Windows.

ci: Only run manifests/generate targets on test target

---

docs/reference/deployments/deployment-yml.md
pkg/deployment/deployment_item.go
pkg/deployment/utils/apply_utils.go
pkg/types/deployment.go
pkg/types/zz_generated.deepcopy.go

This commit adds a new feature that allows users to include a custom message when creating barriers. With this enhancement, users can provide additional information or context related to the barrier, which will be displayed when waiting on the barrier. This feature enhances the usability and flexibility of the barrier functionality. It also updates the project documentation to reflect the recent enhancement regarding optional custom messages for barriers. The documentation now includes clear instructions and examples on how to utilize the message parameter when creating barriers to provide custom messages.
The implementation includes the necessary updates to the barrier creation logic to accept a custom message. Additionally, the cli output has been updated to display the custom message …

feat: Add ability to include custom message in barriers

---

pkg/deployment/external_args.go
pkg/types/deployment.go
pkg/types/git_project.go
pkg/types/git_url.go
pkg/types/result/compact.go
pkg/types/yaml_url.go
pkg/utils/uo/uo.go
pkg/webui/ui/.gitignore

Otherwise custom unmarshallers ignore unknown fields, e.g. in `GitProject`.

fix: Use strict yaml unmarshalling in custom unmarshallers

---

config/rbac/kustomization.yaml
config/rbac/reconciler_binding.yaml
install/controller/controller/rbac.yaml

This binding was missing after the copy from the legacy flux-kluctl-controller.

fix: Add missing cluster-admin binding for the controller

---

cmd/kluctl/commands/cmd_seal.go
e2e/deployment_items_test.go
e2e/test-utils/project.go
pkg/kluctl_project/project.go
pkg/kluctl_project/project_load.go
pkg/kluctl_project/target_context.go

This allows `./foo` to include `../base` when Kluctl is run from inside `foo`.

fix: Fix inclusion of relative base dirs when the project is not at the repo root

---

cmd/kluctl/commands/utils.go
docs/reference/gitops/spec/v1beta1/kluctldeployment.md
pkg/deployment/deployment_item.go

This fixes the new "kluctl controller install" sub-command.

fix: Use projectDir as repoRoot in case there is no Git repo involved

---

pkg/deployment/commands/result_utils.go

This will fix an error message at the end of the "kluctl controller install" command, which was shown even after the actual deployment succeeded.

fix: Don't show error when addGitInfo fails

---

.github/workflows/nightly.yml

Otherwise parallel runs might end up creating a mixed/broken devel release.

ci: Only allow a single nightly workflow to run

---

cmd/kluctl/commands/cobra_utils.go

Otherwise args from ~/.kluctl/config can't contain bools/ints.

fix: Properly convert viber bool/int to string args

---

api/v1beta1/condition_types.go
api/v1beta1/kluctldeployment_types.go
api/v1beta1/zz_generated.deepcopy.go
cmd/kluctl/commands/cmd_deploy.go
config/crd/bases/gitops.kluctl.io_kluctldeployments.yaml
docs/reference/commands/deploy.md
docs/reference/gitops/api/kluctl-controller.md
e2e/gitops_errors_test.go
e2e/prune_test.go
e2e/results_test.go
install/controller/controller/crd.yaml
pkg/controllers/kluctl_project.go
pkg/controllers/kluctldeployment_controller.go
pkg/deployment/commands/delete.go
pkg/deployment/commands/deploy.go
pkg/deployment/commands/prune.go
pkg/deployment/utils/delete_utils.go
pkg/git/test_git_server.go

This implements the `--prune` flag for the deploy command and changes the controller to perform pruning as part of the deploy phase.

feat: Implement pruning right after deploying

---

cmd/kluctl/commands/cmd_webui.go
cmd/kluctl/commands/root.go
hack/prepare-release.sh
install/webui/.kluctl.yaml
install/webui/deployment.yaml
install/webui/webui/admin-rbac.yaml
install/webui/webui/deployment.yaml
install/webui/webui/webui-rbac.yaml
pkg/controllers/kluctl_project.go
pkg/k8s/client_factory.go
pkg/k8s/k8s_cluster.go
pkg/kluctl_project/target_context.go
pkg/webui/auth.go
pkg/webui/clusteraccessor.go
pkg/webui/server.go
pkg/webui/validator.go

This is the start of the impersonation implementation that will later also impersonate groups, mapped via OIDC. For now, it only impersonates the kluctl-webui-admin RBAC user.
This PR also adds a deployment for the webui.

feat: Implement webui impersonation and add a deployment for the webui

---

cmd/kluctl/args/project.go
docs/reference/commands/common-arguments.md
e2e/gitops_test.go
e2e/results_test.go

Command results will be written by default from now on. This way, the webui can show all past results.

feat: Enable writing of command results by default

---

config/manager/manager.yaml
install/controller/controller/manager.yaml

This PR sets the seccompProfile of the controller deployment to comply with the restricted PodSecurity policy.
Fixes #569 
I have tested that it deploys successfully without the previously present warning and continues working once deployed.

fix: Set seccompProfile for controller deployment

---

cmd/kluctl/commands/cmd_helm_update.go

This adds some tracing to find an incompatibility between go-git and git.

fix: Add some tracing when the worktree or index is unclean

---

.github/workflows/nightly.yml

No need to release nightlies just to re-release the queued one as well.
- [x Bug fix (non-breaking change which fixes an issue)

ci: Cancel obsolete nightly workflows

---

e2e/render_test.go
e2e/test-utils/project.go
pkg/kluctl_project/target_context.go

This allows to call render without any kubeconfig available.
Fixes #599

fix: Allow to run render without a KUBECONFIG being present

---

go.mod
go.sum

This upgrades go-jinja2 to the latest main version, which contains a fix for the handling of symlinks in RenderDirectory. Symlinks are now simply re-created in the target directory.
Fixes #474

fix: Upgrade go-jinja2 to fix symlinks handling in RenderDirectory

---

pkg/webui/generate-ts/main.go
pkg/webui/ui/src/api.tsx
pkg/webui/ui/src/models-static.ts
pkg/webui/ui/src/models.ts

There are still old command results in some clusters that have string based refs...these need to be properly parsed by the webui as well.

fix: Add non-generated version of GitRef to react code that supports loading a string

---

.goreleaser.yaml

The bin/ parent folder caused the install.sh script to fail.
Fixes #628

fix: Strip bin parent folder from release tarballs

---

.github/workflows/preview-proxy.yml

Otherwise it tries to wait for the run on the main branch.

ci: Use github.head_ref when waiting for preview-run to finish

---

.github/workflows/preview-proxy.yml
.github/workflows/preview-run.yml

I did not find a way to reliably get the ref of the head from the source PR. This solution is an alternative and should be good enough.

ci: Stop using lewagon/wait-on-check-action and instead ping the ipfs node in a loop

---

cmd/kluctl/commands/cmd_controller_run.go
docs/reference/commands/controller-run.md
go.mod
pkg/controllers/kluctldeployment_controller.go
pkg/controllers/kluctldeployment_controller_setup.go

This re-enables concurrent reconciliation and defaults it to 4.

feat: Add --concurrency flag to controller run

---

cmd/kluctl/commands/cmd_helm_pull.go
cmd/kluctl/commands/cmd_helm_update.go
cmd/kluctl/commands/cmd_render.go
cmd/kluctl/commands/cmd_seal.go
cmd/kluctl/commands/command_result.go
cmd/kluctl/commands/root.go
pkg/deployment/utils/apply_utils.go
pkg/deployment/utils/hooks_util.go
pkg/deployment/utils/remote_objects_utils.go
pkg/git/mirrored_repo.go
pkg/git/utils.go
pkg/helm/helm_release.go
pkg/k8s/k8s_cluster.go
pkg/kluctl_project/targets.go
pkg/registries/registries.go
pkg/repocache/cache.go
pkg/results/result-store-secrets.go
pkg/seal/sealer.go
pkg/status/promts.go
pkg/status/status.go
pkg/webui/server.go

This should avoid `%(MISSING)` inside messages when a `%` is part of the message.

fix: Explicitely decide if status message is formatted or not

---

pkg/deployment/deployment_collection.go
pkg/deployment/deployment_item.go
pkg/deployment/utils/apply_utils.go
pkg/deployment/utils/delete_utils.go
pkg/helm/helm_release.go
pkg/k8s/k8s_cluster.go
pkg/k8s/utils.go
pkg/utils/uo/k8s_fields.go

When a deployment also contains CRDs, the k8s client will not know if an object is namespaced before the CRD is actually applied. This leads to flaky behaviour between the initial and all other deployments.
This commit delays fixing of namespaces until all objects are rendered. Then it takes CRDs into account when determining if an object is namespaced or not.

fix: Take deployed CRDs into account when fixing namespaces

---

pkg/deployment/commands/deploy.go
pkg/deployment/commands/prune.go
pkg/deployment/commands/utils.go

Don't treat object as orphan when they actually got deleted via namespace pruning.

fix: Also consider deleted namespaces when filtering orphans

---

e2e/deployment_items_test.go
pkg/deployment/deployment_item.go

This fixes a bug that caused kustomize bases to not work anymore due to errors reported by CheckSubInDir.
Fixes #684

fix: Fix CheckSubInDir inside ListSealedSecrets

---

docs/reference/deployments/kustomize.md

It looks like the example introduced in #421 does not work, which caused a lot of confusion and issue for multiple people. This PR removes the example and instead simply refers to the deployment-yml.md docs.

docs: Remove bogus Kustomize example and refer to deployment-yml.md

---

cmd/kluctl/commands/cmd_controller_run.go
e2e/test-utils/kluctl_execute.go
pkg/results/result-store-secrets.go

This will make the controller to clean up orphan results whenever a KluctlDeployment gets deleted.

feat: Implement cleanup of orphan command and validate results

---

install/controller/.kluctl.yaml
install/controller/controller/kustomization.yaml
install/webui/.kluctl.yaml
install/webui/webui/deployment.yaml
install/webui/webui/kustomization.yaml

In order to be able to schedule the controller and/or the webui on specific nodes with higher priority when installing them, this PR adds the support for nodeSelector, tolerations and the priorityClassName as arguments for the deployment.
Fixes # None

Support nodeSelector, tolerations and priorityClassName when installing the controller and/or webui

---

install/webui/webui/deployment.yaml

This PR adds an empty env field to the webui deployment because the patch operation is not working without it.
Fixes None

fix: Add empty env to webui install deployment

---

pkg/deployment/utils/diff_utils.go

This fixes issues that mostly happen in tests, where deployments with different object names but same diff-name happen too fast.

fix: Use name as tie-breaker in calcRemoteObjectsForDiff

---

pkg/deployment/utils/apply_utils.go

Otherwise it prints the `default` namespace as things are being simulated in case a new namespace is involved.

fix: Print real ref when warning about about simulated CRDs while dry-running

---

e2e/gitops_test.go

This fixes swallowed logs in tests.

tests: Call ctrl.SetLogger at init() time

---

docs/kluctl/templating/variable-sources.md
install/controller/.kluctl.yaml
install/controller/controller/kustomization.yaml

In order to use gcpSecretManager in kluctl controller with [workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) kluctl service account should be annotated with `iam.gke.io/gcp-service-account` meta information.
This PR adds `controller_service_account_annotations` arg and documentation with example on how to use that.

feat: Allow to set service account annotations

---

.goreleaser.yaml
Dockerfile

git cli is failing with error message `/usr/bin/git: /lib64/libc.so.6: version 'GLIBC_2.38' not found (required by /usr/bin/git)` on WOLFI_DIGEST=sha256:e8411b9629bd13123a978a2d1a27c3ee64c7751d3032ce80ad6e673e329ef964
Reproduce with:
```
docker run -it --platform linux/amd64 --entrypoint /bin/sh ghcr.io/kluctl/kluctl:v2.22.0-devel
~ $ git
/usr/bin/git: /lib64/libc.so.6: version `GLIBC_2.38' not found (required by /usr/bin/git)
```
Commit in wolfi that possibly related:
https://github.com/wolfi-dev/os/commit/a03efaa8be7f0e744795e98315a26ec9ee4222fb

Fix: git cli failing on latest devel

---

e2e/gitops_suite.go

These are so slow that they easily timeout. Also, no one would ever run the controller on windows...right?

tests: Skip gitops tests on windows

---

docs/gitops/spec/v1beta1/kluctldeployment.md
e2e/gitops_misc_test.go
pkg/controllers/kluctl_project.go

This fixes an issue reported on Slack. The controller ignored `spec.source.git.path` and `spec.source.oci.path` and instead only used the deprecated `spec.source.path`.

fix: Fix spec.source.git.path to be actually respected

---

pkg/deployment/utils/apply_utils.go

There are situations where conflict resolution fails. In that case, allow to use `--force-replace-on-error` to solve it.

fix: Allow to retry with force-replace when conflict resolution fails

---

docs/kluctl/deployments/annotations/all-resources.md
pkg/deployment/utils/delete_utils.go

If set to "true", Kluctl will always treat the annotated resource as being managed by Kluctl, meaning that it will
consider it for deletion and pruning even if a foreign field manager resets/removes the Kluctl field manager.

feat: Introduce the kluctl.io/force-managed annotation

---

e2e/args_test.go
e2e/gitops_misc_test.go
e2e/gitops_suite_test.go
e2e/no_target_test.go
pkg/kluctl_project/target-context/target_context.go

This makes `-t` mandatory when the `.kluctl.yaml` defines targets.
Fixes #470

feat: Make -t mandatory when the project defines targets

---

cmd/kluctl/commands/command_result.go

This makes it easier to spot warnings. If they are printed at the top, its easy to miss warnings completely if many changes are present.

feat: Print warning at the bottom of the pretty command result output

---

Dockerfile
cmd/kluctl/commands/root.go
cmd/kluctl/commands/utils.go
e2e/deployment_items_test.go
e2e/gitops_git_include_test.go
e2e/gitops_misc_test.go
e2e/gitops_oci_include_test.go
e2e/oci_include_test.go
e2e/source_override_test.go
e2e/test-utils/test_git_server.go
e2e/test_project/kluctl_execute.go
e2e/test_project/project.go
go.mod
go.sum
pkg/controllers/kluctl_project.go
pkg/controllers/kluctldeployment_controller_source.go
pkg/helm/chart.go
pkg/k8s/discovery.go
pkg/kluctl_jinja2/jinja2.go
pkg/oci/auth_provider/docker_config_auth_provider.go
pkg/repocache/git_cache.go
pkg/repocache/oci_cache.go
pkg/sourceoverride/proxyclient_cli.go
pkg/types/git_url.go
pkg/utils/tmpdir.go
pkg/vars/vars_test.go

Instead of storing everything in the kluctl-workdir inside the tmp dir, use the users cache dirs.
Fixes #389

feat: Use users cache dir for everything cache related

---

e2e/gitops_errors_test.go
e2e/gitops_git_include_test.go
e2e/gitops_helm_test.go
e2e/gitops_misc_test.go
e2e/gitops_oci_include_test.go
e2e/helm_test.go
pkg/controllers/kluctldeployment_controller_status.go
pkg/deployment/utils/apply_utils.go

k9s easily dies when columns get too long. This avoids writing too long statuses into the Ready condition.

fix: Shorten prepare errors to avoid killing k9s and friends

---

pkg/deployment/deployment_collection.go
pkg/deployment/deployment_project.go
pkg/deployment/utils/diff_utils.go
pkg/diff/normalize.go
pkg/diff/normalize_test.go
pkg/kluctl_project/external_args.go
pkg/kluctl_project/targets.go
pkg/types/deployment.go
pkg/types/kluctl_project.go
pkg/types/zz_generated.deepcopy.go
pkg/vars/vars_loader.go
pkg/webui/server.go

Otherwise stuff like this results in crashes:
```yaml
targets:
- null
```
Fixes #325

fix: Do not use slices of struct pointers in yaml related structs

---

.goreleaser.yaml
Dockerfile

Bump wolfi image to latest
Fixes git fetch in v.2.23.0
```
building kustomize objects for /xxx/infra/reloader failed. accumulating resources: accumulation err='accumulating resources from 'https://github.com/stakater/Reloader/deployments/kubernetes?submodules=false': URL is a git repository': failed to run '/usr/bin/git fetch --depth=1 https://github.com/stakater/Reloader HEAD': /usr/libexec/git-core/git-remote-https: /usr/lib/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /usr/lib/libcurl.so.4)\n: exit status 128\n\t* prepare failed with 1 errors. Check status.lastPrepareError for details\n\n",
```
https://github.com/kluctl/kluctl/issues/952

fix: Bump wolfi image to latest

---

e2e/readiness_test.go
pkg/deployment/utils/apply_utils.go

hooks have their own waitReadiness logic, so we must skip them here. Otherwise we'd wait for an object didn't even get deployed yet (e.g. post-deploy hooks).

fix: Skip hooks when determining objects to wait for readiness

---

docs/kluctl/deployments/annotations/all-resources.md
e2e/prune_test.go
pkg/deployment/utils/delete_utils.go
pkg/utils/uo/k8s_fields.go
pkg/utils/uo/uo.go

This allows to instruct Kluctl to force handling of an object as "managed by Kluctl", even if all field ownership is lost or ownerReferences have been added to an object.

feat: Unconditionally assume an object is managed by Kluctl if kluctl.io/force-managed=true

---

go.mod
go.sum

This upgrades go-jinja2 to the latest commit, which uses a go-embed-python version that can be used by Nix maintainers to patch the python binaries properly before packaging.

chore: Upgrade go-jinja2

---

cmd/kluctl/commands/cmd_validate.go
e2e/hooks_test.go
e2e/utils.go
e2e/validate_test.go
pkg/controllers/kluctl_project.go
pkg/controllers/kluctldeployment_controller_reconcile.go
pkg/deployment/commands/validate.go
pkg/deployment/utils/hooks_util.go

This causes `validate` to ignore hooks when they are only meant to be run on deletion.

fix: Ignore delete hooks on validation

---

pkg/utils/uo/jsonpath.go

This fixes a crash reported in Slack.

fix: Fix crash in GetFirstObject that happens if a nil list is encountered

---

pkg/kluctl_project/targets.go
pkg/utils/utils.go

This fixes issues when templating is used inside the global aws config. Without deep cloning, the config gets rendered for the first target and then causes all targets to share the same config, even though rendering was supposed to give different results per target.

fix: Also deep-clone aws config in buildTarget

---

.github/workflows/check-links-cron.yml
Makefile
docs/kluctl/templating/filters.md
docs/kluctl/templating/functions.md
go.mod
go.sum
lychee.toml

This PR partially fixes `get_var` being unable to access local variables. The fix is in go-jinja2: https://github.com/kluctl/go-jinja2/pull/32. It is only a partial fix because loop variables can still not be accessed directly and need a workaround (see the docs). The Jinja2 issue in that regard can be found here: https://github.com/pallets/jinja/issues/1478
This PR also deprecates the render filter and introduces the render global function, as it turns out that filters do not have access to local variables at all.

fix: Partially fix access to loop variables in get_var/render

---

go.mod
pkg/git/mirrored_repo.go
pkg/utils/watchdog.go

A user has reported repeatedly hanging Kluctl controllers. After looking at stack traced, it looks like go-git is not respecting timeouts/deadlines when errors happen. This MR has a workaround for go-git not respecting deadlines. Kluctl will now panic in that case to avoid hanging forever.

fix: Panic when deadline is exceeded too much while fetching from git

---

cmd/kluctl/args/misc.go
cmd/kluctl/commands/cmd_diff.go
docs/kluctl/commands/diff.md
pkg/deployment/commands/diff.go
pkg/deployment/deployment_project.go
pkg/deployment/utils/diff_utils.go

This ass `--ignore-kluctl-metadata`, useful in larger refactorings/migrations.

feat: Implement --ignore-kluctl-metadata

---

pkg/deployment/deployment_item.go
pkg/deployment/utils/apply_utils.go
pkg/deployment/utils/delete_utils.go
pkg/deployment/utils/remote_objects_utils.go
pkg/helm/helm_release.go
pkg/k8s/resources.go
pkg/vars/vars_loader.go

Sometimes individual resources inside a group do not have an APIResource with a version that matches the preferred version of the group. In that case, we must use the latest version instead.
Before this, such resources were completely ignored/skipped, leading to orphan detection to not work for these resources.

fix: Reimplement GetFilteredPreferredGVKs to account for resources without PV

---

e2e/remote_objects_permission_test.go
e2e/test-utils/envtest_cluster.go
e2e/test_resources/example-crds.yaml
e2e/test_resources/resources.go
e2e/validate_test.go
pkg/deployment/commands/validate.go
pkg/deployment/utils/apply_utils.go
pkg/validation/validation.go

This makes the permission errors seen in situations like in #1011 to be warning instead. This PR also adds a fallback that tries to get the required information by trying a sub-resource GET on the status.
Fixes #1011

fix: Fix errors when validating objects without permissions to get the CRDs

---

cmd/kluctl/commands/cmd_oci_push.go

fix: Don't crash on oci push when git repo has no remote

---

pkg/utils/uo/nested_fields.go

A user reported a crash in `GetK8sLabels()` that happened due to `null` label values. This PR fixes this.

fix: Don't crash in uo.GetNestedStringMapCopy in case of null strings

---

pkg/deployment/commands/result_utils.go
pkg/deployment/utils/apply_utils.go
pkg/deployment/utils/delete_utils.go

Multiple potential crashes were discovered when working in offline mode. Some happen only when the offline-mode happens unexpectedly, e.g. when the kubeconfig is empty.

fix: Fix multiple crashes when there is no k8s client available

---

pkg/webui/auth.go
pkg/webui/auth_oidc.go

This is a workaround for https://github.com/golang/oauth2/issues/718

fix: Use a temporary copy of the oauth2 config while refreshing tokens

---

cmd/kluctl/commands/cmd_helm_pull.go
cmd/kluctl/commands/cmd_helm_update.go
e2e/gitops_helm_test.go
e2e/helm_test.go
e2e/test-utils/test_git_server.go
e2e/test_project/project.go
pkg/deployment/deployment_item.go

This contains multiple fixes in regard to pre-pulling inside kluctl libraries. See individual commits.
Fixes #1036

fix: Fix pre-pulled Helm charts in kluctl libraries

---

pkg/helm/chart.go
pkg/helm/helm_release.go

This fixes an issue reported by @netthier in Slack. The controller tried to determined the pre-pulled path of a chart with pre-pulling disabled, which it should not do.

fix: Don't try to find pre-pulled chart when skipPrePull is true

---

pkg/webui/utils.go

A user reported panics in the webui logs when deployed to the cluster. This should fix the panics caused by swallowing Go errors and thus causing nil pointer references.

fix: Don't swallow errors when accepting websockets

---

docs/kluctl/deployments/helm.md

chartName can not be specified when repo is a OCI url

docs: adjust OCI based repo example

---

cmd/kluctl/commands/cmd_helm_update.go
e2e/helm_test.go

This pull request enhances the functionality of the `kluctl helm-update` command to provide users with more information. Now, in addition to searching for updates of the Helm chart, the command will also display the current version of the Helm chart if a newer version is available. This improvement aims to offer greater visibility into the version status of Helm charts.
Implements (#415)
- [ x] New feature (non-breaking change which adds functionality)

feat: show current version of helm chart if a new version is available

---

cmd/kluctl/commands/cmd_webui_run.go
docs/kluctl/commands/webui-run.md
docs/webui/installation.md
pkg/webui/server.go
pkg/webui/ui/src/components/Router.tsx

This introduces `--path-prefix` to `kluctl webui run`.
Fixes #1078

feat: Support running the webui under different path prefixes

---

e2e/discriminator_test.go
pkg/kluctl_project/project.go
pkg/kluctl_project/target-context/target_context.go
pkg/kluctl_project/targets.go

This fixes many potential issues with defaulting and rendering of templated config. For example, the default aws config was not copied into the no-name target.

fix: Generate and render no-name target in loadTargets, same as other targets

---

docs/kluctl/templating/functions.md
go.mod
go.sum

This introduces the `load_base64` function which allows to load binary data as base64 encoded strings.
Fixes #1108

feat: Introduce load_base64 function

---

pkg/diff/normalize.go
pkg/diff/normalize_test.go

In addition to the already ignored but deprecated non-prefixed controller-uid labels.

fix: Also ignore batch.kubernetes.io/controller-uid labels in diffs

---

go.mod
go.sum

This updates all internal Python dependencies.

chore: Update go-jinja2 to latest main

---

go.mod
lib/go.mod

No need to have 1.22.4 as minimum go version. This caused builds on some systems to fail.

chore: Reduce required go version to 1.22.0

---

Dockerfile

This prevented dependabot from updating wolfi-base images.

ci: Stop using intermediate WOLFI_IMAGE arg

---

cmd/kluctl/commands/cmd_list_targets.go
cmd/kluctl/commands/command_result.go

The kluctl command `list-targets`now has an additional flag `--only-names` to filter the output to just include the name of the defined targets.
Usage:
`kluctl list-targets --only-names`
Fixes https://github.com/kluctl/kluctl/issues/678

feat(list-targets): add a flag which allows to filter the output to show only target names

---

install/webui/webui/deployment.yaml

This PR fixes the seccompProfile configuration for the webui deployment by setting it to `RuntimeDefault`.
The fix was locally tested with a Talos Kubernetes cluster to ensure the warning mentioned in the related issue is resolved.
Fixes #1220

fix: apply RuntimeDefault seccompProfile in webui deployment

---

cmd/kluctl/commands/cmd_delete.go
cmd/kluctl/commands/cmd_deploy.go
cmd/kluctl/commands/cmd_diff.go
cmd/kluctl/commands/cmd_poke_images.go
cmd/kluctl/commands/cmd_prune.go
cmd/kluctl/commands/cmd_render.go
cmd/kluctl/commands/cmd_validate.go
cmd/kluctl/commands/command_result.go
cmd/kluctl/commands/utils.go

For example, we should not have the timeout active when writing the command result, which must also be possible when the timeout hit while deploying.
This should fix many test flakes where a timeout returns failure of writing command results instead of the original timeout error.

fix: Only use timeout restricted context for actual work, not the things around

---

.github/workflows/tests.yml

macos-12 is not supported anymore. See https://github.com/actions/runner-images/issues/10721

ci: Switch to macos-13 in CI

---

lychee.toml

This should fix many flaky CI runs.

ci: Ignore gnu.org link in link checking

---

pkg/results/result-store-secrets.go

This avoids crashing afterwards and instead shows an error.
Fixes #1289

fix: Return error instead of nil when command result can't be found

---

pkg/results/result-store-secrets.go

Turns out label values have stricter limits in length then resource names, meaning that we can't use labels to store the deployment names. Using annotations instead of labels solves this.
These labels were luckily never used anywhere and their only meaning was for informational purposes when manually looking into the result objects. 
Fixes #1290

fix: Store deployment name/namespace for results in annotations instead of labels

---

pkg/controllers/kluctldeployment_controller_reconcile.go
pkg/controllers/kluctldeployment_controller_status.go

This should fix a few test flakes where the `lastPrepareError` is unexpectedly empty.

fix: Immediately patch lastPrepareError instead of doing it at the end of the reconciliation

---

docs/kluctl/templating/variable-sources.md
pkg/types/vars_source.go
pkg/types/zz_generated.deepcopy.go
pkg/vars/vars_loader.go
pkg/vars/vars_loader_http.go
pkg/vars/vars_loader_test.go
pkg/webui/ui/src/models.ts

This implements multidoc support for vars sources that are based on parsing yaml content (e.g. file, git, http, ...)

feat: Implement multidoc support for vars sources
